# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 08:07
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(default='xxx.jpg', editable=False, max_length=200)),
                ('order', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lot', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='比赛地图', editable=False, max_length=50)),
                ('cover', models.CharField(default='xxx.jpg', editable=False, max_length=200)),
                ('creatorid', models.IntegerField()),
                ('ispubic', models.BooleanField()),
                ('place', models.CharField(default='比赛地点', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='比赛房间', editable=False, max_length=50)),
                ('createrid', models.IntegerField()),
                ('code', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('detail', models.CharField(default='暂无详情', editable=False, max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Room_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name=app.models.User)),
                ('score', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('isquit', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Room_User_Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(default='xxx.jpg', editable=False, max_length=200)),
                ('lon', models.FloatField()),
                ('lot', models.FloatField()),
                ('uptime', models.DateTimeField()),
                ('room_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room_User')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(default='越野用户', editable=False, max_length=50)),
                ('sex', models.CharField(editable=False, max_length=1)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=80)),
                ('avatar', models.CharField(default='xxx.jpg', editable=False, max_length=200)),
                ('signature', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match'),
        ),
    ]
