# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160407_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='这个人很懒，什么都没有留下', max_length=200),
        ),
    ]
