# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:10
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160407_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('headImg', models.FileField(upload_to=app.models.content_file_name)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='createrid',
            new_name='creatorid',
        ),
        migrations.AddField(
            model_name='match',
            name='uploadtime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 13, 1, 10, 27, 705217, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='room',
            name='createtime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 13, 1, 10, 27, 705217, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='room',
            name='creatorname',
            field=models.CharField(default='xxx', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
