# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160413_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='uploadtime',
            field=models.TimeField(blank=True, default=datetime.datetime(2016, 4, 13, 1, 13, 5, 931438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='createtime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 13, 1, 13, 5, 931438, tzinfo=utc)),
        ),
    ]
