# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160413_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='uploadtime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='createtime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 13, 1, 13, 22, 494719, tzinfo=utc)),
        ),
    ]
