# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160413_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='createtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
