# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160416_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='lot',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ispubic',
            new_name='ispublic',
        ),
    ]
